# Generated by Django 2.2.5 on 2019-09-17 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='action',
            name='desc',
            field=models.CharField(help_text='备注信息', max_length=512, null=True, verbose_name='备注信息'),
        ),
        migrations.AlterField(
            model_name='action',
            name='id',
            field=models.AutoField(editable=False, help_text='主键', primary_key=True, serialize=False, verbose_name='主键'),
        ),
        migrations.AlterField(
            model_name='action',
            name='is_active',
            field=models.BooleanField(default=True, help_text='是否可用', verbose_name='是否可用'),
        ),
        migrations.AlterField(
            model_name='action',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, help_text='更新时间', null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='action',
            name='name',
            field=models.CharField(help_text='名称', max_length=32, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='action',
            name='operate',
            field=models.CharField(help_text='操作', max_length=32, verbose_name='操作'),
        ),
        migrations.AlterField(
            model_name='denyaccount',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='denyaccount',
            name='desc',
            field=models.CharField(help_text='备注信息', max_length=512, null=True, verbose_name='备注信息'),
        ),
        migrations.AlterField(
            model_name='denyaccount',
            name='id',
            field=models.AutoField(editable=False, help_text='主键', primary_key=True, serialize=False, verbose_name='主键'),
        ),
        migrations.AlterField(
            model_name='denyaccount',
            name='is_active',
            field=models.BooleanField(default=True, help_text='是否可用', verbose_name='是否可用'),
        ),
        migrations.AlterField(
            model_name='denyaccount',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, help_text='更新时间', null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='denyaccount',
            name='open_data',
            field=models.DateTimeField(auto_now=True, help_text='解封时间', null=True, verbose_name='解封时间'),
        ),
        migrations.AlterField(
            model_name='denyaccount',
            name='user',
            field=models.ForeignKey(help_text='用户', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='denyip',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='denyip',
            name='desc',
            field=models.CharField(help_text='备注信息', max_length=512, null=True, verbose_name='备注信息'),
        ),
        migrations.AlterField(
            model_name='denyip',
            name='id',
            field=models.AutoField(editable=False, help_text='主键', primary_key=True, serialize=False, verbose_name='主键'),
        ),
        migrations.AlterField(
            model_name='denyip',
            name='ip',
            field=models.GenericIPAddressField(help_text='IP地址', verbose_name='IP地址'),
        ),
        migrations.AlterField(
            model_name='denyip',
            name='is_active',
            field=models.BooleanField(default=True, help_text='是否可用', verbose_name='是否可用'),
        ),
        migrations.AlterField(
            model_name='denyip',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, help_text='更新时间', null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='denyip',
            name='open_data',
            field=models.DateTimeField(auto_now=True, help_text='解封时间', null=True, verbose_name='解封时间'),
        ),
        migrations.AlterField(
            model_name='group',
            name='actions',
            field=models.ManyToManyField(help_text='包含行为', through='admin.GroupAction', to='admin.Action', verbose_name='包含行为'),
        ),
        migrations.AlterField(
            model_name='group',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='group',
            name='desc',
            field=models.CharField(help_text='备注信息', max_length=512, null=True, verbose_name='备注信息'),
        ),
        migrations.AlterField(
            model_name='group',
            name='id',
            field=models.AutoField(editable=False, help_text='主键', primary_key=True, serialize=False, verbose_name='主键'),
        ),
        migrations.AlterField(
            model_name='group',
            name='is_active',
            field=models.BooleanField(default=True, help_text='是否可用', verbose_name='是否可用'),
        ),
        migrations.AlterField(
            model_name='group',
            name='menus',
            field=models.ManyToManyField(help_text='包含菜单', through='admin.GroupMenu', to='admin.Menu', verbose_name='包含菜单'),
        ),
        migrations.AlterField(
            model_name='group',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, help_text='更新时间', null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(help_text='名称', max_length=32, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='group',
            name='roles',
            field=models.ManyToManyField(help_text='包含角色', through='admin.GroupRole', to='admin.Role', verbose_name='包含角色'),
        ),
        migrations.AlterField(
            model_name='groupaction',
            name='action',
            field=models.ForeignKey(help_text='行为', on_delete=django.db.models.deletion.CASCADE, to='admin.Action', verbose_name='行为'),
        ),
        migrations.AlterField(
            model_name='groupaction',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='groupaction',
            name='desc',
            field=models.CharField(help_text='备注信息', max_length=512, null=True, verbose_name='备注信息'),
        ),
        migrations.AlterField(
            model_name='groupaction',
            name='group',
            field=models.ForeignKey(help_text='群组', on_delete=django.db.models.deletion.CASCADE, to='admin.Group', verbose_name='群组'),
        ),
        migrations.AlterField(
            model_name='groupaction',
            name='id',
            field=models.AutoField(editable=False, help_text='主键', primary_key=True, serialize=False, verbose_name='主键'),
        ),
        migrations.AlterField(
            model_name='groupaction',
            name='is_active',
            field=models.BooleanField(default=True, help_text='是否可用', verbose_name='是否可用'),
        ),
        migrations.AlterField(
            model_name='groupaction',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, help_text='更新时间', null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='groupmenu',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='groupmenu',
            name='desc',
            field=models.CharField(help_text='备注信息', max_length=512, null=True, verbose_name='备注信息'),
        ),
        migrations.AlterField(
            model_name='groupmenu',
            name='group',
            field=models.ForeignKey(help_text='群组', on_delete=django.db.models.deletion.CASCADE, to='admin.Group', verbose_name='群组'),
        ),
        migrations.AlterField(
            model_name='groupmenu',
            name='id',
            field=models.AutoField(editable=False, help_text='主键', primary_key=True, serialize=False, verbose_name='主键'),
        ),
        migrations.AlterField(
            model_name='groupmenu',
            name='is_active',
            field=models.BooleanField(default=True, help_text='是否可用', verbose_name='是否可用'),
        ),
        migrations.AlterField(
            model_name='groupmenu',
            name='menu',
            field=models.ForeignKey(help_text='菜单', on_delete=django.db.models.deletion.CASCADE, to='admin.Menu', verbose_name='菜单'),
        ),
        migrations.AlterField(
            model_name='groupmenu',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, help_text='更新时间', null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='grouprole',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='grouprole',
            name='desc',
            field=models.CharField(help_text='备注信息', max_length=512, null=True, verbose_name='备注信息'),
        ),
        migrations.AlterField(
            model_name='grouprole',
            name='group',
            field=models.ForeignKey(help_text='群组', on_delete=django.db.models.deletion.CASCADE, to='admin.Group', verbose_name='群组'),
        ),
        migrations.AlterField(
            model_name='grouprole',
            name='id',
            field=models.AutoField(editable=False, help_text='主键', primary_key=True, serialize=False, verbose_name='主键'),
        ),
        migrations.AlterField(
            model_name='grouprole',
            name='is_active',
            field=models.BooleanField(default=True, help_text='是否可用', verbose_name='是否可用'),
        ),
        migrations.AlterField(
            model_name='grouprole',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, help_text='更新时间', null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='grouprole',
            name='role',
            field=models.ForeignKey(help_text='角色', on_delete=django.db.models.deletion.CASCADE, to='admin.Role', verbose_name='角色'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='desc',
            field=models.CharField(help_text='备注信息', max_length=512, null=True, verbose_name='备注信息'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='icon',
            field=models.CharField(help_text='图标', max_length=32, null=True, verbose_name='图标'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='id',
            field=models.AutoField(editable=False, help_text='主键', primary_key=True, serialize=False, verbose_name='主键'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='is_active',
            field=models.BooleanField(default=True, help_text='是否可用', verbose_name='是否可用'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='is_outer',
            field=models.BooleanField(default=False, help_text='是否外链', verbose_name='是否外链'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, help_text='更新时间', null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(help_text='名称', max_length=32, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, help_text='排序', null=True, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='parent',
            field=models.ForeignKey(help_text='父菜单', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='admin.Menu', verbose_name='父菜单'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='url',
            field=models.CharField(help_text='地址', max_length=128, null=True, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='address',
            field=models.CharField(help_text='地址', max_length=256, null=True, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='charge',
            field=models.CharField(help_text='负责人', max_length=64, null=True, verbose_name='负责人'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='desc',
            field=models.CharField(help_text='备注信息', max_length=512, null=True, verbose_name='备注信息'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='id',
            field=models.AutoField(editable=False, help_text='主键', primary_key=True, serialize=False, verbose_name='主键'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='is_active',
            field=models.BooleanField(default=True, help_text='是否可用', verbose_name='是否可用'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, help_text='更新时间', null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(help_text='名称', max_length=64, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, help_text='排序', null=True, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='parent',
            field=models.ForeignKey(help_text='父机构', null=True, on_delete=django.db.models.deletion.CASCADE, to='admin.Organization', verbose_name='父机构'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='phone',
            field=models.CharField(help_text='电话号码', max_length=32, null=True, verbose_name='联系电话'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='position',
            field=django_mysql.models.JSONField(default=dict, help_text='坐标', null=True, verbose_name='经纬度'),
        ),
        migrations.AlterField(
            model_name='role',
            name='actions',
            field=models.ManyToManyField(help_text='包含行为', through='admin.RoleAction', to='admin.Action', verbose_name='包含行为'),
        ),
        migrations.AlterField(
            model_name='role',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='role',
            name='desc',
            field=models.CharField(help_text='备注信息', max_length=512, null=True, verbose_name='备注信息'),
        ),
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.AutoField(editable=False, help_text='主键', primary_key=True, serialize=False, verbose_name='主键'),
        ),
        migrations.AlterField(
            model_name='role',
            name='is_active',
            field=models.BooleanField(default=True, help_text='是否可用', verbose_name='是否可用'),
        ),
        migrations.AlterField(
            model_name='role',
            name='menus',
            field=models.ManyToManyField(help_text='包含菜单', through='admin.RoleMenu', to='admin.Menu', verbose_name='包含菜单'),
        ),
        migrations.AlterField(
            model_name='role',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, help_text='更新时间', null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(help_text='名称', max_length=64, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='roleaction',
            name='action',
            field=models.ForeignKey(help_text='行为', on_delete=django.db.models.deletion.CASCADE, to='admin.Action', verbose_name='行为'),
        ),
        migrations.AlterField(
            model_name='roleaction',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='roleaction',
            name='desc',
            field=models.CharField(help_text='备注信息', max_length=512, null=True, verbose_name='备注信息'),
        ),
        migrations.AlterField(
            model_name='roleaction',
            name='id',
            field=models.AutoField(editable=False, help_text='主键', primary_key=True, serialize=False, verbose_name='主键'),
        ),
        migrations.AlterField(
            model_name='roleaction',
            name='is_active',
            field=models.BooleanField(default=True, help_text='是否可用', verbose_name='是否可用'),
        ),
        migrations.AlterField(
            model_name='roleaction',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, help_text='更新时间', null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='roleaction',
            name='role',
            field=models.ForeignKey(help_text='角色', on_delete=django.db.models.deletion.CASCADE, to='admin.Role', verbose_name='角色'),
        ),
        migrations.AlterField(
            model_name='rolemenu',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='rolemenu',
            name='desc',
            field=models.CharField(help_text='备注信息', max_length=512, null=True, verbose_name='备注信息'),
        ),
        migrations.AlterField(
            model_name='rolemenu',
            name='id',
            field=models.AutoField(editable=False, help_text='主键', primary_key=True, serialize=False, verbose_name='主键'),
        ),
        migrations.AlterField(
            model_name='rolemenu',
            name='is_active',
            field=models.BooleanField(default=True, help_text='是否可用', verbose_name='是否可用'),
        ),
        migrations.AlterField(
            model_name='rolemenu',
            name='menu',
            field=models.ForeignKey(help_text='菜单', on_delete=django.db.models.deletion.CASCADE, to='admin.Menu', verbose_name='菜单'),
        ),
        migrations.AlterField(
            model_name='rolemenu',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, help_text='更新时间', null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='rolemenu',
            name='role',
            field=models.ForeignKey(help_text='角色', on_delete=django.db.models.deletion.CASCADE, to='admin.Role', verbose_name='角色'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(help_text='头像', null=True, upload_to='', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(help_text='生日', null=True, verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cellphone',
            field=models.CharField(help_text='手机号码', max_length=32, null=True, unique=True, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='configure',
            field=django_mysql.models.JSONField(default=dict, help_text='个人配置', null=True, verbose_name='用户配置'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, help_text='更新时间', null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='desc',
            field=models.CharField(help_text='描述', max_length=512, null=True, verbose_name='备注信息'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='电子邮箱', max_length=254, null=True, unique=True, verbose_name='电子邮件'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.IntegerField(choices=[(1, 'MALE'), (2, 'FEMALE'), (0, 'UNKNOWN')], default=0, help_text='性别', null=True, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(help_text='组', null=True, through='admin.UserGroup', to='admin.Group', verbose_name='用户-组'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_card',
            field=models.CharField(help_text='身份证号', max_length=32, null=True, unique=True, verbose_name='身份证'),
        ),
        migrations.AlterField(
            model_name='user',
            name='organizations',
            field=models.ManyToManyField(help_text='组织机构', through='admin.UserOrganization', to='admin.Organization', verbose_name='用户-机构'),
        ),
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(help_text='角色', null=True, through='admin.UserRole', to='admin.Role', verbose_name='用户-角色'),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='desc',
            field=models.CharField(help_text='备注信息', max_length=512, null=True, verbose_name='备注信息'),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='group',
            field=models.ForeignKey(help_text='群组', on_delete=django.db.models.deletion.CASCADE, to='admin.Group'),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='id',
            field=models.AutoField(editable=False, help_text='主键', primary_key=True, serialize=False, verbose_name='主键'),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='is_active',
            field=models.BooleanField(default=True, help_text='是否可用', verbose_name='是否可用'),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, help_text='更新时间', null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='user',
            field=models.ForeignKey(help_text='用户', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userorganization',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='userorganization',
            name='desc',
            field=models.CharField(help_text='备注信息', max_length=512, null=True, verbose_name='备注信息'),
        ),
        migrations.AlterField(
            model_name='userorganization',
            name='id',
            field=models.AutoField(editable=False, help_text='主键', primary_key=True, serialize=False, verbose_name='主键'),
        ),
        migrations.AlterField(
            model_name='userorganization',
            name='is_active',
            field=models.BooleanField(default=True, help_text='是否可用', verbose_name='是否可用'),
        ),
        migrations.AlterField(
            model_name='userorganization',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, help_text='更新时间', null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='userorganization',
            name='organization',
            field=models.ForeignKey(help_text='机构', on_delete=django.db.models.deletion.CASCADE, to='admin.Organization'),
        ),
        migrations.AlterField(
            model_name='userorganization',
            name='user',
            field=models.ForeignKey(help_text='用户', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='desc',
            field=models.CharField(help_text='备注信息', max_length=512, null=True, verbose_name='备注信息'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='id',
            field=models.AutoField(editable=False, help_text='主键', primary_key=True, serialize=False, verbose_name='主键'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='is_active',
            field=models.BooleanField(default=True, help_text='是否可用', verbose_name='是否可用'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, help_text='更新时间', null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.ForeignKey(help_text='角色', on_delete=django.db.models.deletion.CASCADE, to='admin.Role'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='user',
            field=models.ForeignKey(help_text='用户', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='verifycode',
            name='cellphone',
            field=models.CharField(help_text='手机号', max_length=32, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='verifycode',
            name='code',
            field=models.CharField(help_text='验证码', max_length=6, verbose_name='验证码'),
        ),
        migrations.AlterField(
            model_name='verifycode',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='verifycode',
            name='desc',
            field=models.CharField(help_text='备注信息', max_length=512, null=True, verbose_name='备注信息'),
        ),
        migrations.AlterField(
            model_name='verifycode',
            name='id',
            field=models.AutoField(editable=False, help_text='主键', primary_key=True, serialize=False, verbose_name='主键'),
        ),
        migrations.AlterField(
            model_name='verifycode',
            name='is_active',
            field=models.BooleanField(default=True, help_text='是否可用', verbose_name='是否可用'),
        ),
        migrations.AlterField(
            model_name='verifycode',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, help_text='更新时间', null=True, verbose_name='更新时间'),
        ),
    ]
