# Generated by Django 2.2.5 on 2019-09-17 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_auto_20190917_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(help_text='群组', through='admin.UserGroup', to='admin.Group', verbose_name='用户-组'),
        ),
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(help_text='角色', through='admin.UserRole', to='admin.Role', verbose_name='用户-角色'),
        ),
    ]
