# Generated by Django 2.2.5 on 2019-09-18 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_auto_20190917_1811'),
    ]

    operations = [
        migrations.RenameField(
            model_name='denyaccount',
            old_name='open_data',
            new_name='open_date',
        ),
        migrations.RenameField(
            model_name='denyip',
            old_name='open_data',
            new_name='open_date',
        ),
        migrations.AlterField(
            model_name='organization',
            name='parent',
            field=models.ForeignKey(help_text='父机构', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='admin.Organization', verbose_name='父机构'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(help_text='头像', null=True, upload_to='avatar', verbose_name='头像'),
        ),
    ]
