# Generated by Django 2.2.5 on 2019-09-18 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0004_auto_20190918_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='name',
            field=models.CharField(help_text='名称', max_length=32, unique=True, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='denyaccount',
            name='open_date',
            field=models.DateTimeField(help_text='解封时间', null=True, verbose_name='解封时间'),
        ),
        migrations.AlterField(
            model_name='denyip',
            name='open_date',
            field=models.DateTimeField(help_text='解封时间', null=True, verbose_name='解封时间'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(help_text='名称', max_length=32, unique=True, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(help_text='名称', max_length=32, unique=True, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='order',
            field=models.PositiveSmallIntegerField(help_text='排序', null=True, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(help_text='名称', max_length=64, unique=True, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(help_text='名称', max_length=64, unique=True, verbose_name='名称'),
        ),
    ]
